import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Chatbot from "@/components/chatbot";
import { Chakra_Petch } from "next/font/google";

const chakraPetch = Chakra_Petch({
  subsets: ["latin"], 
  weight: ["400", "500", "700"], // chọn các độ dày bạn muốn
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "EcoVerse",
  description: "Generated by create next app",
  icons: { icon: "/logo.png" }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="p-[32px] bg-[#F2F2F2]">
      {/* Đặt chatbot nổi không ảnh hưởng bởi các component khác */}
      <Chatbot/>
      <body
        className={`${chakraPetch.className}  antialiased bg-[#F2F2F2]`} 
      >
        
        <Header  />
        {children}
        <Footer />
      </body>
    </html>
  );
}
